create table customer(
    id int generated by default as identity,
    customer_number varchar(20),
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    street varchar(100),
    house_number varchar(20),
    zip_code varchar(10),
    place varchar(100),
    phone_number varchar(20),
    primary key (id));

alter table customer
    add constraint UQ_CUSTOMER_NUMBER UNIQUE (customer_number) ;
